---
- block:

    - name: "Ensure existense of /tmp/blackbox_exporter-v{{ blackbox_exporter_version }}"
      ansible.builtin.file:
        path: "/tmp/blackbox_exporter-v{{ blackbox_exporter_version }}"
        state: directory

    - name: Unarchive blackbox_exporter
      become: false
      unarchive:
        src: "{{ blackbox_exporter_repo_dir }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/blackbox_exporter-v{{ blackbox_exporter_version }}"
        creates: "/tmp/blackbox_exporter-v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter"
      check_mode: false

    - name: "Copy blackbox_exporter to {{ blackbox_exporter_install_dir }}"
      ansible.builtin.copy:
        src: "/tmp/blackbox_exporter-v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter"
        dest: "{{ blackbox_exporter_install_dir }}/blackbox_exporter"
        owner: root
        group: root
        mode: 0755
        remote_src: yes
      notify: restart blackbox_exporter

- name: Ensure blackbox exporter binary has cap_net_raw capability
  capabilities:
    path: "{{ blackbox_exporter_install_dir }}/blackbox_exporter"
    capability: cap_net_raw+ep
    state: present
  when: not ansible_check_mode
