---
- name: Create blackbox_exporter system group
  group:
    name: "{{ blackbox_exporter_system_group }}"
    state: present
    system: true
  when: blackbox_exporter_system_group != "root"

- name: Create blackbox_exporter system user
  user:
    name: "{{ blackbox_exporter_system_user }}"
    groups: "{{ blackbox_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: blackbox_exporter_system_user != "root"
